In [19]:
from env import make_env

In [20]:
import matplotlib.pyplot as plt

In [21]:
env = make_env('cpu', 3)

/home/yoosoo/anaconda3/envs/mujoco/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
env.show_cube = True

In [ ]:
env.init_state()

In [ ]:
env.fig

In [ ]:
env.reset()

In [ ]:
env.fig

In [ ]:
from pycuber import *

def isSolved(sim_cube):
    solved = True
    if sim_cube.D == [[Square(sim_cube["D"].colour)] * 3] * 3:
        for face in "LFRB":
            if sim_cube.get_face(face)[:] != [[Square(sim_cube[face].colour)] * 3] * 3:
                solved = False
    else:
        solved = False
    return solved

In [ ]:
env2 = make_env('cpu', 3)

In [ ]:
env2.show_cube = True

In [ ]:
env2.init_state()

In [ ]:
env2.fig

In [ ]:
env2.sim_cube

In [ ]:
isSolved(env2.sim_cube)

In [ ]:
env2.sim_cube.perform_step("U")

In [ ]:
action = 0
face, degree = env.action_to_sim_action['render'][action]
env2.fig.axes[3].rotate_face(face, degree, layer = 0)
env2.fig

In [ ]:
isSolved(env2.sim_cube)

In [ ]:
env2.init_state()
env2.sim_cube.perform_step("U")
for action in range(env2.action_dim):
    # print("########################################")
    print(env2.sim_cube)
    sim_action = env2.action_to_sim_action[env2.cube_size][action]
    # next_sim_cube = env2.sim_cube.perform_step(sim_action)
    # print(next_sim_cube)
    if action % 2 == 0:
        counter_action = action + 1
    else:
        counter_action = action - 1
    if isSolved(env2.sim_cube.perform_step(sim_action)):
        reward = 1.0
        target_value, target_policy = 1.0, action
        print("Solved!")
        print(env2.sim_cube)
        print(env2.action_to_sim_action[env2.cube_size][counter_action])
        break
    else:
        reward = -1.0
    env2.sim_cube.perform_step(env2.action_to_sim_action[env2.cube_size][counter_action])
    
    # if isSolved_(next_sim_cube) == 1:
    

In [ ]:
env3 = make_env('cpu', 3)

In [ ]:
env3.show_cube = True

In [ ]:
env3.sim_cube

In [ ]:
import copy

In [ ]:
state = env3.sim_state_to_state(env3.sim_cube)

In [ ]:
env3.sim_cube.perform_step("U")

In [ ]:
next_state = env3.sim_state_to_state(env3.sim_cube)

In [ ]:
state == next_state

In [ ]:
if next_cube.D == [[Square(next_cube["D"].colour)] * 3] * 3:
    for face in "LFRB":
        if next_cube.get_face(face)[:] != [[Square(next_cube[face].colour)] * 3] * 3:
            print("Not Solved!")

In [ ]:
next_cube.perform_step("U'")

In [ ]:
if next_cube.D == [[Square(next_cube["D"].colour)] * 3] * 3:
    for face in "LFRB":
        if next_cube.get_face(face)[:] != [[Square(next_cube[face].colour)] * 3] * 3:
            print("Not Solved!")
else:
    print("Not Solved!")

In [ ]:
import yaml

In [ ]:
with open('./config/config.yaml') as f:
    cfg = yaml.safe_load(f)

In [ ]:
hidden_dim = cfg['model']['hidden_dim']

In [ ]:
hidden_dim

In [43]:
import numpy as np

In [44]:
moveInds = { \
  "U": 0, "U'": 1, "F": 2, "F'": 3, "R": 4, "R'": 5, 
  "D": 6, "D'": 7, "B": 8, "B'": 9, "L": 10, "L'": 11
}

In [45]:
corner_pieceDefs = np.array([ \
  [ 0, 47, 36], \
  [ 6, 38, 18], \
  [ 8, 20,  9], \
  [ 2, 11, 45], \
  [33, 42, 53], \
  [27, 24, 44], \
  [29, 26, 15], \
  [35, 51, 17], \
])

In [46]:
edge_pieceDefs = np.array([\
  [  1, 46], \
  [  3, 37], \
  [  7, 19], \
  [  5, 10], \
  [ 34, 52], \
  [ 30, 43], \
  [ 28, 25], \
  [ 32, 16], \
  [ 21, 41], \
  [ 23, 12], \
  [ 48, 14], \
  [ 50, 39], \
    ])

In [47]:
moveDefs = np.array([ \
# U
[    6,  3,  0,  7,  4,  1,  8,  5,  2, \
    45, 46, 47, 12, 13, 14, 15, 16, 17, \
     9, 10, 11, 21, 22, 23, 24, 25, 26, \
    27, 28, 29, 30, 31, 32, 33, 34, 35, \
    18, 19, 20, 39, 40, 41, 42, 43, 44, \
    36, 37, 38, 48, 49, 50, 51, 52, 53],\
# U'
[   2,  5,  8,  1,  4,  7,  0,  3,  6,  \
    18, 19, 20, 12, 13, 14, 15, 16, 17, \
    36, 37, 38, 21, 22, 23, 24, 25, 26, \
    27, 28, 29, 30, 31, 32, 33, 34, 35, \
    45, 46, 47, 39, 40, 41, 42, 43, 44, \
     9, 10, 11, 48, 49, 50, 51, 52, 53],\
# F
[   0,  1,  2,  3,  4,  5, 44,  41, 38, \
    6,  10, 11, 7, 13, 14, 8, 16, 17,   \
    24, 21, 18, 25, 22, 19, 26, 23, 20, \
    15, 12, 9, 30, 31, 32, 33, 34, 35,  \
    36, 37, 27, 39, 40, 28, 42, 43, 29, \
    45, 46, 47, 48, 49, 50, 51, 52, 53],\
# F'   
[   0,  1,  2,  3,  4,  5,  9,  12,  15,  \
    29,  10, 11, 28, 13, 14, 27, 16, 17, \
    20, 23, 26, 19, 22, 25, 18, 21, 24, \
    38, 41, 44, 30, 31, 32, 33, 34, 35, \
    36, 37, 8, 39, 40, 7, 42, 43, 6, \
    45, 46, 47, 48, 49, 50, 51, 52, 53],\
# R
[   0,  1,  20,  3,  4,  23,  6,  7,  26,  \
    15,  12, 9, 16, 13, 10, 17, 14, 11, \
    18, 19, 29, 21, 22, 32, 24, 25, 35, \
    27, 28, 51, 30, 31, 48, 33, 34, 45, \
    36, 37, 38, 39, 40, 41, 42, 43, 44, \
    8, 46, 47, 5, 49, 50, 2, 52, 53],\
# R'
[   0,  1,  51,  3,  4,  48,  6,  7,  45,  \
    11,  14, 17, 10, 13, 16, 9, 12, 15, \
    18, 19, 2, 21, 22, 5, 24, 25, 8, \
    27, 28, 20, 30, 31, 23, 33, 34, 26, \
    36, 37, 38, 39, 40, 41, 42, 43, 44, \
    35, 46, 47, 32, 49, 50, 29, 52, 53],\
# D
# 5th: 51, 52, 53 -> 53, 52, 51
[   0,  1,  2,  3,  4,  5,  6,  7,  8,  \
    9,  10, 11, 12, 13, 14, 24, 25, 26, \
    18, 19, 20, 21, 22, 23, 42, 43, 44, \
    33, 30, 27, 34, 31, 28, 35, 32, 29, \
    36, 37, 38, 39, 40, 41, 53, 52, 51, \
    45, 46, 47, 48, 49, 50, 15, 16, 17],\
# D'
# 6th: 42, 43, 44 -> 44, 43, 42
[   0,  1,  2,  3,  4,  5,  6,  7,  8,  \
    9,  10, 11, 12, 13, 14, 51, 52, 53, \
    18, 19, 20, 21, 22, 23, 15, 16, 17, \
    29, 32, 35, 28, 31, 34, 27, 30, 33, \
    36, 37, 38, 39, 40, 41, 24, 25, 26, \
    45, 46, 47, 48, 49, 50, 44, 43, 42],\

# B
[   11,  14,  7,  3,  4,  5,  6,  7,  8,  \
    9,  10, 35, 12, 13, 34, 15, 16, 33, \
    18, 19, 20, 21, 22, 23, 24, 25, 26, \
    27, 28, 29, 30, 31, 32, 36, 39, 42, \
    2, 37, 38, 1, 40, 41, 0, 43, 44, \
    51, 48, 45, 52, 49, 46, 53, 50, 47],\
# B'
# 5th: 25 -> 35
[   42,  39,  36,  3,  4,  5,  6,  7,  8,  \
    9,  10, 0, 12, 13, 1, 15, 16, 2, \
    18, 19, 20, 21, 22, 23, 24, 25, 26, \
    27, 28, 29, 30, 31, 32, 17, 14, 11, \
    33, 37, 38, 34, 40, 41, 35, 43, 44, \
    47, 50, 53, 46, 49, 52, 45, 48, 51],\
# L
# L face 수정완료
# 4th: 18, 21, 24 -> 24, 21, 18
[   53,  1,  2,  50,  4,  5,  47,  7,  8,  \
    9,  10, 11, 12, 13, 14, 15, 16, 17, \
    0, 19, 20, 3, 22, 23, 6, 25, 26, \
    24, 28, 29, 21, 31, 32, 18, 34, 35, \
    42, 39, 36, 43, 40, 37, 44, 41, 38, \
    45, 46, 33, 48, 49, 30, 51, 52, 27],\
# L'
# 3th: 53 -> 27
[   18,  1,  2,  21,  4,  5,  24,  7,  8,  \
    9,  10, 11, 12, 13, 14, 15, 16, 17, \
    27, 19, 20, 30, 22, 23, 33, 25, 26, \
    53, 28, 29, 50, 31, 32, 47, 34, 35, \
    38, 41, 44, 37, 40, 43, 36, 39, 42, \
    45, 46, 6, 48, 49, 3, 51, 52, 0],\

])# [12, 54]

In [48]:
def initState_3():
    return np.array([
        0, 0, 0, 0, 0, 0, 0, 0, 0,\
        1, 1, 1, 1, 1, 1, 1, 1, 1,\
        2, 2, 2, 2, 2, 2, 2, 2, 2,\
        3, 3, 3, 3, 3, 3, 3, 3, 3,\
        4, 4, 4, 4, 4, 4, 4, 4, 4,\
        5, 5, 5, 5, 5, 5, 5, 5, 5])

In [49]:
def doMove_3(s, move):
    move = moveInds[move]
    return s[moveDefs[move]]

In [50]:
s = initState_3()

In [51]:
s[corner_pieceDefs]

array([[0, 5, 4],
       [0, 4, 2],
       [0, 2, 1],
       [0, 1, 5],
       [3, 4, 5],
       [3, 2, 4],
       [3, 2, 1],
       [3, 5, 1]])

In [52]:
s[edge_pieceDefs]

array([[0, 5],
       [0, 4],
       [0, 2],
       [0, 1],
       [3, 5],
       [3, 4],
       [3, 2],
       [3, 1],
       [2, 4],
       [2, 1],
       [5, 1],
       [5, 4]])

In [53]:
corner_hashOP = np.array([1, 2, 10])

In [54]:
np.dot(s[corner_pieceDefs], corner_hashOP)

array([50, 28, 14, 52, 61, 47, 17, 23])

In [55]:
edge_hashOP = np.array([1, 10])

In [56]:
np.dot(s[edge_pieceDefs], edge_hashOP)

array([50, 40, 20, 10, 53, 43, 23, 13, 42, 12, 15, 45])

In [57]:
corner_cases = {}
s = initState_3()
corner_cases['init'] = np.dot(s[corner_pieceDefs], corner_hashOP)
for action in moveInds.keys():   
    s = doMove_3(s, action)
    corner_cases[action] = np.dot(s[corner_pieceDefs], corner_hashOP)
    s = initState_3()

In [58]:
corner_cases

{'init': array([50, 28, 14, 52, 61, 47, 17, 23]),
 'U': array([28, 14, 52, 50, 61, 47, 17, 23]),
 "U'": array([52, 50, 28, 14, 61, 47, 17, 23]),
 'F': array([50, 30,  8, 52, 61, 35,  5, 23]),
 "F'": array([50, 21, 35, 52, 61,  8, 38, 23]),
 'R': array([50, 28, 18,  4, 61, 47, 21, 15]),
 "R'": array([50, 28, 15, 37, 61, 47, 12, 18]),
 'D': array([50, 28, 14, 52, 23, 61, 31, 25]),
 "D'": array([50, 28, 14, 52, 47, 25, 55, 61]),
 'B': array([11, 28, 14, 56, 54, 47, 17, 44]),
 "B'": array([44, 28, 14, 54, 57, 47, 17, 11]),
 'L': array([51, 13, 14, 52, 40, 42, 17, 23]),
 "L'": array([42, 40, 14, 52, 13, 51, 17, 23])}

In [59]:
edge_cases = {}
s = initState_3()
edge_cases['init'] = np.dot(s[edge_pieceDefs], edge_hashOP)
for action in moveInds.keys():   
    s = doMove_3(s, action)
    edge_cases[action] = np.dot(s[edge_pieceDefs], edge_hashOP)
    s = initState_3()

In [63]:
edge_cases = {}
s = initState_3()
edge_cases['init'] = np.dot(s[edge_pieceDefs], edge_hashOP)
for action in ["U'", "F"]:
    s = doMove_3(s, action)
edge_cases[action] = np.dot(s[edge_pieceDefs], edge_hashOP)
edge_cases

{'init': array([50, 40, 20, 10, 53, 43, 23, 13, 42, 12, 15, 45]),
 'F': array([10, 50, 24, 20, 53, 43, 21, 13, 32,  4, 15, 45])}

In [64]:
edge_cases

{'init': array([50, 40, 20, 10, 53, 43, 23, 13, 42, 12, 15, 45]),
 'F': array([10, 50, 24, 20, 53, 43, 21, 13, 32,  4, 15, 45])}

In [ ]:
def isSolved_3(s):
  for i in range(6):
    if not (s[9 * i:9 * i + 9] == s[9 * i]).all():
      return False
  return True

In [ ]:
isSolved_3(s)

In [ ]:
edge_cases = {}
s = initState_3()
edge_cases['init'] = np.dot(s[edge_pieceDefs], edge_hashOP)
for action in "UR":
    s = doMove_3(s, action)
    edge_cases[action] = np.dot(s[edge_pieceDefs], edge_hashOP)
edge_cases


In [ ]:
from gym_cube.envs.assets.py222 import py222 as p2

In [ ]:
p2_cases = {}
ps = p2.initState()
p2_cases['init'] = np.dot(ps[p2.pieceDefs], p2.hashOP)
for action in p2.moveInds.keys():
    ps = p2.doMove(ps, action)
    p2_cases[action] = np.dot(ps[p2.pieceDefs], p2.hashOP)
    ps = p2.initState()
p2_cases

In [ ]:
corner_hashOP = np.array([1, 2, 10]) # 3d
edge_hashOP = np.array([1, 10]) # 2d

# [max hash number, [cubelet position, face position]] z y x
corner_pieceInds = np.zeros([62, 2], dtype=np.int)
corner_pieceInds[50] = [0, 0]; corner_pieceInds[54] = [0, 1]; corner_pieceInds[13] = [0, 2]
corner_pieceInds[28] = [1, 0]; corner_pieceInds[ 8] = [1, 1]; corner_pieceInds[42] = [1, 2]
corner_pieceInds[14] = [2, 0]; corner_pieceInds[ 5] = [2, 1]; corner_pieceInds[12] = [2, 2]
corner_pieceInds[52] = [3, 0]; corner_pieceInds[11] = [3, 1]; corner_pieceInds[15] = [3, 2]

corner_pieceInds[61] = [4, 0]; corner_pieceInds[44] = [4, 1]; corner_pieceInds[51] = [4, 2]
corner_pieceInds[47] = [5, 0]; corner_pieceInds[30] = [5, 1]; corner_pieceInds[60] = [5, 2]
corner_pieceInds[17] = [6, 0]; corner_pieceInds[35] = [6, 1]; corner_pieceInds[18] = [6, 2]
corner_pieceInds[23] = [7, 0]; corner_pieceInds[56] = [7, 1]; corner_pieceInds[21] = [7, 2]

edge_pieceInds = np.zeros([55, 2], dtype=np.int)
# 40과 43이 중복이다 왜??
edge_pieceInds[50] = [0, 0]; edge_pieceInds[5] = [0, 1]
edge_pieceInds[40] = [1, 0]; edge_pieceInds[40] = [1, 1]
edge_pieceInds[20] = [2, 0]; edge_pieceInds[2] = [2, 1]
edge_pieceInds[10] = [3, 0]; edge_pieceInds[13] = [3, 1]

edge_pieceInds[53] = [4, 0]; edge_pieceInds[35] = [4, 1]
edge_pieceInds[43] = [5, 0]; edge_pieceInds[43] = [5, 1]
edge_pieceInds[23] = [6, 0]; edge_pieceInds[32] = [6, 1]
edge_pieceInds[13] = [7, 0]; edge_pieceInds[13] = [7, 1]

edge_pieceInds[42] = [8, 0]; edge_pieceInds[24] = [8, 1]
edge_pieceInds[12] = [9, 0]; edge_pieceInds[21] = [9, 1]

edge_pieceInds[15] = [10, 0]; edge_pieceInds[51] = [10, 1]
edge_pieceInds[45] = [11, 0]; edge_pieceInds[54] = [11, 1]

In [ ]:
def pos_to_state_3(pos):
    # pos: 20, 2 -> [cube name, [cubelet position, face position]]
    # state: 20, 24
    state = np.zeros([20, 24], dtype=np.int)
    for position, pos_element in enumerate(pos):
        if position < 8:
            state_value = pos_element[0] * 3 + pos_element[1]
        else:
            state_value = pos_element[0] * 2 + pos_element[1]
    
        state[position][state_value] = 1.0
    return state


In [ ]:
def getOP_3(s):
    corner_op = corner_pieceInds[np.dot(s[corner_pieceDefs], corner_hashOP)]
    edge_op = edge_pieceInds[np.dot(s[edge_pieceDefs], edge_hashOP)]
    return np.concatenate((corner_op, edge_op))

In [ ]:
s = initState_3()
pos = getOP_3(s)
pos

In [ ]:
state = pos_to_state_3(pos)

In [ ]:
state

In [ ]:
for move in moveDefs:
    move = np.sort(np.array(move))
    print(move)

In [24]:
import pycuber as pc

In [40]:
c = pc.Cube()

In [41]:
c

In [42]:
c.perform_step("L")